### PR TITLE
Updated the docker files, and package-locks

### LINKED ISSUE #9: Resolving security vulnerabilities in dependent packages
Really nice work on this project David! Congrats 🎉

## What you did:
- I forked the repository
- Connected it with snyk.io
- Observed the security scan results

## What happened:
Great stuff here: Dockerfile uses alpine ✅ Server-side code doesn't use any packages with known vulnerabilities ✅

However I found several vulnerabilities on the frontend related code:

image

## Problem description:

When cloning the project for personal use, Snyk alerts me of security vulnerabilities.

## Suggested solution:

Some of the security vulnerabilities reported on dependent packages can be resolved by using newer versions of them (so an update to the lockfile is needed).

### PR DESCRIPTION
**Pull request by boyney123**
Attempt to fix #9.

### CODE REVIEW

**Comment by boyney123** [comment]
Not 💯 sure if this is all correct, I couldn't work out how to replace the `tar` `vulnerability` as something is using version 2.2.1, I updated most things to latest, but still causing issues?

@lirantal I have also updated a few more things:

- Using `npm ci` in the docker images to install from `package-lock`
- Updated `package-lock` files to tie down versions and remove some vulnerabilities

Is that normally best practice?

**Comment by Hongarc** [comment]
`react-scripts > fsevents > node-pre-gyp > tar` will be fixed in next release facebook/create-react-app@e11ebfa (fsevents@2.0.6 don't use node-pre-gyp)

`node-sass > node-gyp > tar` will be fixed in next release too nodejs/node-gyp@1456ef2

**Comment by lirantal** [comment]
Looks better. We're down to 4 vulnerabilities:
image

As @Hongarc mentioned, we'll need to wait for releases to be made to address the other vulnerable packages. Perhaps consider connecting snyk with the github project to monitor it and open fix PRs when remediation is available.

>Updated package-lock files to tie down versions and remove some vulnerabilities

You didn't edit that file manually, right? You can trigger new nested dependencies upgrades by re-installing them.

BTW yarn has a `yarn --freeze-lockfile` argument which works just like `npm ci` in-case this was the reason you switched to npm from yarn.

**Comment by boyney123** [comment]
Ok @lirantal thanks for that. I've seen your other issue #22 which I will also look into to get the auto PR 👍

**Pull request merged**
