### PR TITLE
Add the ability to group routes 

### PR DESCRIPTION
**Pull request by JDansercoer**
**What**:

**BEFORE**
image

**AFTER**
image

**Why**:

We would be using mockit for a plethora of services spread across multiple teams. With no grouping whatsoever it would quickly become a huge mess.
With the ability to group routes, you can quickly hide a whole list of routes that share the same basepath (e.g. you decide on a basepath per team).

**How**:

Added a checkbox to enable grouping.
If it is enabled, all routes will be grouped by their URL, and will be displayed in a parent-child relationship, depicted by indentation. 

I also had to remove the scrollreveal for the routes itself, because the revealing was super bugged when working with the `<detail>` tag.

I also added `styled-components` for more precise styling, so future front-end additions can be done in JS only.
I also split up the route files a little bit more, to ensure a one component per file approach.

**Checklist**:

- [ ] Tests
- [ ] Ready to be merged

I have currently not added tests, as I'm not entirely sure what the front-end testing approach is. If you can elaborate on that, I'll happily add them!

### CODE REVIEW

**Comment by boyney123** [comment]
This looks wicked @JDansercoer!! 

I will take a look and review over the weekend 🙇 👍

**Comment by boyney123** [comment]
Thanks for this @JDansercoer, a great feature and thanks so much for contributing to the project 🙏 .

I am aiming for a 1.1.0 release, which this will part of, I'm going to write up some docs for the feature too.

FYI I made a few changes:

- Added tests
- Fixed Jest tests problems
- Added more test coverage
- Refactored some code and moved components around.

Overall, awesome feature thanks! I will add you to the contributing list too :)

**Comment by JDansercoer** [comment]
All right, awesome! We'll probably be using mockit a lot, so I'll try to expand other features where I deem needed!

**Comment by boyney123** [comment]
@JDansercoer 👍 good stuff.

I have added some docs too.

image

A few other things I'm working on at the moment so will merge 1.1.0 at some point, if you want to use your feature use branch `1.1.0` for now 👍.

Thanks again

**Pull request merged**
