### PR TITLE
feat(security): prevent secrets from leaking to source control

### PR DESCRIPTION
**Pull request by lirantal**
**What**:

Detect secrets when files are committed so we can prevent from these leaking into source contorl.

**Why**:

Adds support through `detect-secrets` which wraps Yelp's generic detect-secrets tool, to test for secrets being committed to source control using the pre-commit framework the project already has, and as a result prevent secrets like passwords, tokens and others to leak into source control.

**How**:

Introduce husky, lint-staged and detect-secrets tool to create pre-commit hooks which will run the detect-secrets-launcher tool to detect detects for files being committed.

The `detect-secrets` npm package will try different methods of invoking the `detect-secrets-hook` tool to run the secrets test for each file, and if it isn't able to find it will silently fail to not interrupt developer workflow. In a future re-visit of this capability we can update this to be a breaking change and fail the commit (or perhaps fail the CI, which might be a bit late, but better than never).

**Checklist**:

- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by lirantal** [comment]
@boyney123 I updated this PR to include the newest version of detect-secrets and the secrets baseline

**Comment by boyney123** [comment]
Awesome, looking good! Love this.

I think it only works in the `server` directory atm, if I make changes in `client` I still can commit.

What do you think? Should we add it to all three projects inside?

image

**Comment by lirantal** [comment]
Yay 🎉

Indeed I only added it specifically to the server project as an early PR. How about we merge so we can push this in without being too far from master's tip and then I'll send another PR to include the client/ project as well?

What is the 3rd project? :-)

**Comment by boyney123** [comment]
Yeah that sounds great. There is:

1. `mockit-routes
2. `server`
3. `client`

I will merge this in soon (il get a minor release out and document the change :) )

**Comment by lirantal** [comment]
Sounds good @boyney123 
I'll then follow it up with a PR to include the other projects as well.

**Pull request merged**
